/* Generated By:JavaCC: Do not edit this line. ProyectoFase3.java */
/** Simple brace matcher. */
public class ProyectoFase3 implements ProyectoFase3Constants {
public static int countloc=0x00;
static int LONGITUD=0;
static String RAD1="";             // Para DN o AN lado derecho
static String RAD2="";             // Para DN o AN Lado izquierdo
static Ensamble ensamblar = new Ensamble();             //Objeto de ensamblar
static int modo=0;             //Cabecera modo de de instruccion
static int EOPMODO=0;               //Cabezara OPMODE de EOR
static int lsir=0;                //Cabecera s/ir
static String data="";               // Guarda el numero de 8 16 y 32
static String bitnumber="";              //Guarda el Numero de 8 16 y 32
static int DR=0;                //saber si es left o right
static int size=0;               // saber si es .w .b .l
static int type=0;             //Tipo de orden en la instruccion
static String Instruct="";
public static TablaSimbolos tabla= new TablaSimbolos();
/** Main entry point. */
public static void main(String args[]) throws ParseException {
        ProyectoFase3 parser = new ProyectoFase3(System.in);
        parser.Estructura();
        System.out.println("Analisis Finalizado:");
}

/*METODOS PARA ESTRUCTURA DEL PROGRAMA*/
  static final public void Estructura() throws ParseException {
        String Inicio="",Etiqueta="";
         System.out.println("Analsisi Inicializado");
    Etiqueta = jj_consume_token(Identificador).image;
    jj_consume_token(ORG);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case D32:
      Inicio = jj_consume_token(D32).image;
      break;
    case D16:
      Inicio = jj_consume_token(D16).image;
      break;
    case D8:
      Inicio = jj_consume_token(D8).image;
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                Inicio=Inicio.substring(1);
                ensamblar.ORG(Inicio,Etiqueta);
    Directivas_Est();
    Instrucciones_Est();
    jj_consume_token(END);
          ensamblar.Imprimir2S1();
          ensamblar.ImprimirS9();
    jj_consume_token(0);
  }

  static final public void Directivas_Est() throws ParseException {
        Token id;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Identificador:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      id = jj_consume_token(Identificador);
      Directivas(id);
    }
  }

  static final public void Instrucciones_Est() throws ParseException {
        Token id;
        String Identi="";
    jj_consume_token(Punto);
    jj_consume_token(CODE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Identificador:
        id = jj_consume_token(Identificador);
                               ensamblar.bandera();
                               if(!tabla.existe(id.image)) {
                                       tabla.insertar(id.image, countloc, "DIR");
                                       Identi=id.image;
                               }
                               else{
                                       System.out.println("Error! el ID \u005c""+id.image+"\u005c" ya existe!");
                                       java.lang.System.exit(1);
                               }
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      Instrucciones(Identi);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADD:
      case CMP:
      case EOR:
      case LSL:
      case LSR:
      case BCHG:
      case PACK:
      case SBCD:
      case JMP:
      case Identificador:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
    }
  }

  static final public void Instrucciones(String Identi) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BCHG:
      BCHG(Identi);
      break;
    case PACK:
      PACK(Identi);
      break;
    case ADD:
      ADD_METODO(Identi);
      break;
    case JMP:
      JMP_Metodo(Identi);
      break;
    case SBCD:
      SBCD(Identi);
      break;
    case CMP:
      CMP(Identi);
      break;
    case LSL:
    case LSR:
      LSL(Identi);
      break;
    case EOR:
      EOR(Identi);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*FIN METODOS PARA ESTRUCTURA DEL PROGRAMA*/

/*METODOS PARA CREAR LAS DIRECTIVAS*/
  static final public void Directivas(Token id) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DDATA:
      DDATA(id);
      break;
    case BYTE:
    case WORD:
    case LONG:
    case EXT:
    case DEF:
    case EQU:
      BWLEDE(id);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void DDATA(Token id) throws ParseException {
        int multi=1;
        String Identi= id.image;
        int bytesOcupados=0;
        String TipoDato="DB";
        Token v;
    jj_consume_token(DDATA);
                int tipo2=Tamanio();
                v=Valor();

                String tipo=v.image;
                int pasarval= Integer.parseInt(tipo.substring(1,tipo.length()),16); //Agregado

                ensamblar.DWLB(4,tipo2,pasarval);

                tipo=tipo.substring(0,1);
                int longitud=0;
                if (tipo=="$"|tipo=="B"|tipo=="0")
                        longitud=v.image.length()-2;
                else
                        longitud=v.image.length()-1;
                int total=0;


                switch(tipo2) {
                case 1 : //DDATA.B
                        total=longitud/2;
                        total += (longitud % 2 == 0) ? 0 : 1;
                        break;
                case 2 : //DDATA.W
                        total=longitud/4;
                        total += (longitud % 4 == 0) ? 0 : 1;
                        total *=2;
                        TipoDato="DW";

                        break;
                case 3 : //DDATA.L
                        total=longitud/8;
                        total += (longitud % 8 == 0) ? 0 : 1;
                        total *=4;

                        TipoDato="DL";
                        break;
                }

                countloc+=total;

                if (!tabla.existe(Identi)) {
                        tabla.insertar(Identi,countloc,TipoDato);
                }
                else{
                        System.out.println("Error el ID \u005c""+Identi+"\u005c"Ya se encuentra");
                        java.lang.System.exit(0);
                }
                tabla.setTam(Identi, total);
  }

  static final public void BWLEDE(Token id) throws ParseException {
        String Identi=id.image;
        int bytes=0;
        int val=0;
        int aux;
        Token v;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BYTE:
      jj_consume_token(BYTE);
                val=1;
      break;
    case WORD:
      jj_consume_token(WORD);
                                val=2;
      break;
    case LONG:
      jj_consume_token(LONG);
                                                val=3;
      break;
    case EQU:
      jj_consume_token(EQU);
      break;
    case EXT:
      jj_consume_token(EXT);
      break;
    case DEF:
      jj_consume_token(DEF);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    v = Valor();
                String p=v.image;
                int pasarval= Integer.parseInt(p.substring(1,p.length()),16); //Agregado
                ensamblar.DWLB(val,val,pasarval);
                if (val!=0) {CONTADORBW(Identi,val,v); }
  }

/*FIN METODOS PARA CREAR LAS DIRECTIVAS*/

/*METODOS INSTRUCCION PACK Y MOVEC*/
/*********************MATTA***************************/
  static final public void PACK(String Identi) throws ParseException {
        int bytesOcupados=0x1;
    jj_consume_token(PACK);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Guion:
      PACK_RM();
      jj_consume_token(Coma);
      PACK_RM();
      break;
    case Datos:
      jj_consume_token(Datos);
      jj_consume_token(Coma);
      jj_consume_token(Datos);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                countloc=(countloc)+(bytesOcupados*2);
                tabla.setTam(Identi, bytesOcupados*2);
  }

  static final public void PACK_RM() throws ParseException {
    jj_consume_token(Guion);
    jj_consume_token(ParentesisA);
    jj_consume_token(Memoria);
    jj_consume_token(ParentesisC);
  }

  static final public void BCHG(String Identi) throws ParseException {
        String tipo="Default";
    jj_consume_token(BCHG);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Punto:
      jj_consume_token(Punto);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LO:
        jj_consume_token(LO);
                            tipo="L";
        break;
      case BY:
        jj_consume_token(BY);
                                             tipo="B";
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    BCHG_VAR(Identi,tipo);
  }

  static final public void BCHG_VAR(String Identi, String tipo) throws ParseException {
        int bytesOcupados=0x1;
        bitnumber="00";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
      RAD1 = jj_consume_token(Datos).image;
      jj_consume_token(Coma);
                                  type=1;
      BCHG_EA(bytesOcupados, Identi,tipo);
      break;
    case Gato:
            type=2;
      jj_consume_token(Gato);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D32:
        bitnumber = jj_consume_token(D32).image;
                                                   bytesOcupados=bytesOcupados+4;
        break;
      case D16:
        bitnumber = jj_consume_token(D16).image;
                                                                                                           bytesOcupados=bytesOcupados+2;
        break;
      case D8:
        bitnumber = jj_consume_token(D8).image;
                                                                                                                                                                  bytesOcupados=bytesOcupados+2;
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(Coma);
      BCHG_EA(bytesOcupados, Identi,tipo);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BCHG_EA(int bytesOcupados, String Identi, String tipo) throws ParseException {
        String ext="";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
      RAD2 = jj_consume_token(Datos).image;
                             modo=0;
      break;
    case Guion:
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      RAD2 = jj_consume_token(Memoria).image;
                                                   modo=4;
      jj_consume_token(ParentesisC);
      break;
    case ParentesisA:
      jj_consume_token(ParentesisA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D8:
      case D16:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case D16:
          ext = jj_consume_token(D16).image;
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case Coma:
            jj_consume_token(Coma);
            RAD2 = jj_consume_token(Memoria).image;
            jj_consume_token(ParentesisC);
                                                                                          bytesOcupados++; modo=5;
            break;
          case ParentesisC:
            jj_consume_token(ParentesisC);
            jj_consume_token(Punto);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case WO:
              jj_consume_token(WO);
                                                                                                                                                 bytesOcupados++; modo=7; RAD2="00";
              break;
            case LO:
              jj_consume_token(LO);
                                                                                                                                                                                            RAD2="01"; bytesOcupados=bytesOcupados+2; modo=7;
              break;
            default:
              jj_la1[12] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
          default:
            jj_la1[13] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        case D8:
          ext = jj_consume_token(D8).image;
          jj_consume_token(Coma);
          RAD2 = jj_consume_token(Memoria).image;
          jj_consume_token(Coma);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case Memoria:
            jj_consume_token(Memoria);
            break;
          case Datos:
            jj_consume_token(Datos);
            break;
          default:
            jj_la1[14] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(ParentesisC);
                                                                                                                bytesOcupados++; modo=6;
          break;
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case Memoria:
        RAD2 = jj_consume_token(Memoria).image;
                                                         modo=2;
        jj_consume_token(ParentesisC);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Mas:
          jj_consume_token(Mas);
                                                                                      modo=3;
          break;
        default:
          jj_la1[16] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                ensamblar.BCHG2(RAD1,RAD2,type,modo,bitnumber,ext);

  }

/*******************FIN*MATTA***************************/
/*FIN METTODOS INSTRUCCION PACK y MOVEC*/

/*METODOS INSTRUCCIONES JMP Y ADD*/
  static final public void JMP_Metodo(String id) throws ParseException {
    jj_consume_token(JMP);
    JMP_Ea(id);
  }

  static final public void JMP_Ea(String id) throws ParseException {
        int bytesOcupados=0x1;
        int multi=2;
        int mode=0;
        String ext="";
    jj_consume_token(ParentesisA);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Memoria:
      RAD1 = jj_consume_token(Memoria).image;
                                  mode=2;
      jj_consume_token(ParentesisC);
      break;
    case D16:
      ext = jj_consume_token(D16).image;
                                                                           bytesOcupados++;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ParentesisC:
        jj_consume_token(ParentesisC);
        jj_consume_token(Punto);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case WO:
          jj_consume_token(WO);
                                                                                                                         bytesOcupados++;mode=7;RAD1="00";
          break;
        case LO:
          jj_consume_token(LO);
                                                                                                                                                                  bytesOcupados+=2;mode=7;RAD1="01";
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case Coma:
        jj_consume_token(Coma);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Memoria:
          RAD1 = jj_consume_token(Memoria).image;
                                                                                                                                                                                                                                     mode=5;
          break;
        case PC:
          jj_consume_token(PC);
                                                                                                                                                                                                                                                    mode=7;RAD1="10";
          break;
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(ParentesisC);
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case D8:
      ext = jj_consume_token(D8).image;
                             bytesOcupados++;
      jj_consume_token(Coma);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Memoria:
        RAD1 = jj_consume_token(Memoria).image;
                                                                            mode=6;
        break;
      case PC:
        jj_consume_token(PC);
                                                                                          mode=7;RAD1="11";
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(Coma);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Datos:
        jj_consume_token(Datos);
        break;
      case Memoria:
        RAD1 = jj_consume_token(Memoria).image;
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(ParentesisC);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          System.out.println("-------------------");
          System.out.println("REGISTER: "+RAD1);
          System.out.println("Mode: "+mode);
          System.out.println("Extension: "+ext);
          System.out.println("----------------");
                countloc+=bytesOcupados*multi;
                tabla.setTam(id,bytesOcupados*multi);
  }

  static final public void ADD_METODO(String id) throws ParseException {
        String tipo="Default";
    jj_consume_token(ADD);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Punto:
      jj_consume_token(Punto);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BY:
        jj_consume_token(BY);
                           tipo="B";
        break;
      case WO:
        jj_consume_token(WO);
                                            tipo="W";
        break;
      case LO:
        jj_consume_token(LO);
                                                             tipo="L";
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
      jj_consume_token(Datos);
      jj_consume_token(Coma);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Guion:
      case ParentesisA:
        ADD_Ea2(id);
        break;
      case Datos:
        jj_consume_token(Datos);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case Guion:
    case ParentesisA:
    case Gato:
    case Memoria:
      ADD_Ea1(id,tipo);
      jj_consume_token(Coma);
      jj_consume_token(Datos);
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void ADD_Ea1(String id,String tipo) throws ParseException {
        int bytesOcupados=0x1;
        int multi=2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Memoria:
      jj_consume_token(Memoria);
      break;
    case Guion:
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      jj_consume_token(Memoria);
      jj_consume_token(ParentesisC);
      break;
    case ParentesisA:
      jj_consume_token(ParentesisA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Memoria:
        jj_consume_token(Memoria);
        jj_consume_token(ParentesisC);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Mas:
          jj_consume_token(Mas);
          break;
        default:
          jj_la1[29] = jj_gen;
          ;
        }
        break;
      case D16:
        jj_consume_token(D16);
                               bytesOcupados++;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Coma:
          jj_consume_token(Coma);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case Memoria:
            jj_consume_token(Memoria);
            break;
          case PC:
            jj_consume_token(PC);
            break;
          default:
            jj_la1[30] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(ParentesisC);
          break;
        case ParentesisC:
          jj_consume_token(ParentesisC);
          jj_consume_token(Punto);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case WO:
            jj_consume_token(WO);
                                                          bytesOcupados++;
            break;
          case LO:
            jj_consume_token(LO);
                                                                                  bytesOcupados+=2;
            break;
          default:
            jj_la1[31] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case D8:
        jj_consume_token(D8);
                              bytesOcupados++;
        jj_consume_token(Coma);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Memoria:
          jj_consume_token(Memoria);
          break;
        case PC:
          jj_consume_token(PC);
          break;
        default:
          jj_la1[33] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(Coma);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Datos:
          jj_consume_token(Datos);
          break;
        case Memoria:
          jj_consume_token(Memoria);
          break;
        default:
          jj_la1[34] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(ParentesisC);
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case Gato:
      jj_consume_token(Gato);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D16:
        jj_consume_token(D16);
                              bytesOcupados+=2;
        break;
      case D32:
        jj_consume_token(D32);
                                                        bytesOcupados+=4;
        break;
      case D8:
        jj_consume_token(D8);
                                                                                 bytesOcupados+=2;
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                countloc+=bytesOcupados*multi;
                tabla.setTam(id,bytesOcupados*multi);
  }

  static final public void ADD_Ea2(String id) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ParentesisA:
      jj_consume_token(ParentesisA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D16:
        jj_consume_token(D16);
        jj_consume_token(ParentesisC);
        jj_consume_token(Punto);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case WO:
          jj_consume_token(WO);
          break;
        case LO:
          jj_consume_token(LO);
          break;
        default:
          jj_la1[38] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case Memoria:
        jj_consume_token(Memoria);
        jj_consume_token(ParentesisC);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Mas:
          jj_consume_token(Mas);
          break;
        default:
          jj_la1[39] = jj_gen;
          ;
        }
        jj_consume_token(D16);
        jj_consume_token(Coma);
        jj_consume_token(Memoria);
        jj_consume_token(ParentesisC);
        break;
      case D8:
        jj_consume_token(D8);
        jj_consume_token(Coma);
        jj_consume_token(Memoria);
        jj_consume_token(Coma);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Datos:
          jj_consume_token(Datos);
          break;
        case Memoria:
          jj_consume_token(Memoria);
          break;
        default:
          jj_la1[40] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(ParentesisC);
        break;
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case Guion:
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      jj_consume_token(Memoria);
      jj_consume_token(ParentesisC);
      break;
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*FIN METODOS INSTRUCCIONES JMP Y ADD*/

/*METODOS INSTRUCCIONES CMP Y SBCD*/
  static final public void SBCD(String id) throws ParseException {
        String tipo="Default";
    jj_consume_token(SBCD);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Punto:
      jj_consume_token(Punto);
      jj_consume_token(BY);
                           tipo="B";
      break;
    default:
      jj_la1[43] = jj_gen;
      ;
    }
    SBCD_VAR(id,tipo);
  }

  static final public void SBCD_VAR(String id,String tipo) throws ParseException {
        int bytesOcupados=0x1;
        int rm=0;
        int registro1=0;
        int registro2=0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
      RAD1 = jj_consume_token(Datos).image;
      jj_consume_token(Coma);
      RAD2 = jj_consume_token(Datos).image;
                                                      rm=0;
      break;
    case Guion:
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      RAD1 = jj_consume_token(Memoria).image;
      jj_consume_token(ParentesisC);
      jj_consume_token(Coma);
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      RAD2 = jj_consume_token(Memoria).image;
      jj_consume_token(ParentesisC);
                                                                                                                                                                               rm=1;
      break;
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                countloc+=bytesOcupados*2;

                registro1=Integer.parseInt(RAD1.substring(1,RAD1.length()));
                registro2=Integer.parseInt(RAD2.substring(1,RAD2.length()));
                tabla.setTam(id,bytesOcupados*2);
                ensamblar.SBCD(registro1,registro2,rm);
  }

/**************************MATTA*********************/
  static final public void CMP(String Identi) throws ParseException {
        String tipo="Default";
    jj_consume_token(CMP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Punto:
      jj_consume_token(Punto);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BY:
        jj_consume_token(BY);
                           tipo="B";
        break;
      case LO:
        jj_consume_token(LO);
                                            tipo="L";
        break;
      case WO:
        jj_consume_token(WO);
                                                             tipo="W";
        break;
      default:
        jj_la1[45] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[46] = jj_gen;
      ;
    }
    CMP_EA(Identi,tipo);
    jj_consume_token(Coma);
    jj_consume_token(Datos);
  }

  static final public void CMP_EA(String Identi, String tipo) throws ParseException {
        int bytesOcupados=0x1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
    case Memoria:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Datos:
        jj_consume_token(Datos);
        break;
      case Memoria:
        jj_consume_token(Memoria);
        break;
      default:
        jj_la1[47] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case Guion:
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      jj_consume_token(Memoria);
      jj_consume_token(ParentesisC);
      break;
    case ParentesisA:
      jj_consume_token(ParentesisA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D8:
      case D16:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case D16:
          jj_consume_token(D16);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case Coma:
            jj_consume_token(Coma);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case Memoria:
              jj_consume_token(Memoria);
                                                          bytesOcupados++;
              break;
            case PC:
              jj_consume_token(PC);
                                                                                  bytesOcupados++;
              break;
            default:
              jj_la1[48] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            jj_consume_token(ParentesisC);
            break;
          case ParentesisC:
            jj_consume_token(ParentesisC);
            jj_consume_token(Punto);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case WO:
              jj_consume_token(WO);
                                                                                                                                               bytesOcupados++;
              break;
            case LO:
              jj_consume_token(LO);
                                                                                                                                                                       bytesOcupados=bytesOcupados+2;
              break;
            default:
              jj_la1[49] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
          default:
            jj_la1[50] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        case D8:
          jj_consume_token(D8);
          jj_consume_token(Coma);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case Memoria:
            jj_consume_token(Memoria);
            break;
          case PC:
            jj_consume_token(PC);
            break;
          default:
            jj_la1[51] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(Coma);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case Memoria:
            jj_consume_token(Memoria);
            break;
          case Datos:
            jj_consume_token(Datos);
            break;
          default:
            jj_la1[52] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(ParentesisC);
                                                                                                  bytesOcupados++;
          break;
        default:
          jj_la1[53] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case Memoria:
        jj_consume_token(Memoria);
        jj_consume_token(ParentesisC);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Mas:
          jj_consume_token(Mas);
          break;
        default:
          jj_la1[54] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[55] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case Gato:
      jj_consume_token(Gato);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D32:
        jj_consume_token(D32);
                      bytesOcupados=bytesOcupados+4;
        break;
      case D16:
        jj_consume_token(D16);
                                                             bytesOcupados=bytesOcupados+2;
        break;
      case D8:
        jj_consume_token(D8);
                                                                                                   bytesOcupados=bytesOcupados+2;
        break;
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[57] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                countloc=(countloc)+(bytesOcupados*2);

                tabla.setTam(Identi, bytesOcupados*2);
  }

/**************************FIN MATTA*********************/
/*FIN METODOS INSTRUCCIONES CMP Y BCSD*/

/*METODOS INSTRUCCIONES EOR Y LSL-LSR*/
/***************************MATTA***********************/
  static final public void LSL(String Identi) throws ParseException {
        String tipo="DEFAULT";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LSL:
      jj_consume_token(LSL);
               DR=1;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Punto:
        jj_consume_token(Punto);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case BY:
          jj_consume_token(BY);
                                     tipo="B"; size=0;
          break;
        case LO:
          jj_consume_token(LO);
                                                              tipo="L"; size=2;
          break;
        case WO:
          jj_consume_token(WO);
                                                                                       tipo="W"; size=1;
          break;
        default:
          jj_la1[58] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[59] = jj_gen;
        ;
      }
      break;
    case LSR:
      jj_consume_token(LSR);
                                                                                                                     DR=0;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Punto:
        jj_consume_token(Punto);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case BY:
          jj_consume_token(BY);
                                                                                                                                           size=0;
          break;
        case LO:
          jj_consume_token(LO);
                                                                                                                                                          size=2;
          break;
        case WO:
          jj_consume_token(WO);
                                                                                                                                                                         size=1;
          break;
        default:
          jj_la1[60] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[61] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[62] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    LSL_VAR(Identi,tipo);
  }

  static final public void LSL_VAR(String Identi, String tipo) throws ParseException {
        int bytesOcupados=0x1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
      RAD1 = jj_consume_token(Datos).image;
      jj_consume_token(Coma);
      RAD2 = jj_consume_token(Datos).image;
                                                    type=1; lsir=1;
      break;
    case Gato:
      jj_consume_token(Gato);
               type =2; lsir=0;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D32:
        data = jj_consume_token(D32).image;
                                                     bytesOcupados=bytesOcupados+4;
        break;
      case D16:
        data = jj_consume_token(D16).image;
                                                                                                        bytesOcupados=bytesOcupados+2;
        break;
      case D8:
        data = jj_consume_token(D8).image;
                                                                                                                                                          bytesOcupados=bytesOcupados+2;
        break;
      default:
        jj_la1[63] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(Coma);
      RAD1 = jj_consume_token(Datos).image;
      break;
    case Guion:
    case ParentesisA:
      LSL_EA(Identi, bytesOcupados,tipo);
                                           type=3;
      break;
    default:
      jj_la1[64] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void LSL_EA(String Identi, int bytesOcupados,String tipo) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Guion:
      jj_consume_token(Guion);
                 modo=4;
      jj_consume_token(ParentesisA);
      RAD1 = jj_consume_token(Memoria).image;
      jj_consume_token(ParentesisC);
      break;
    case ParentesisA:
      jj_consume_token(ParentesisA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D16:
        bitnumber = jj_consume_token(D16).image;
                                         modo=5;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Coma:
          jj_consume_token(Coma);
          RAD2 = jj_consume_token(Memoria).image;
          jj_consume_token(ParentesisC);
                                                                                            bytesOcupados++;
          break;
        case ParentesisC:
          jj_consume_token(ParentesisC);
          jj_consume_token(Punto);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case WO:
            jj_consume_token(WO);
                                                                              bytesOcupados++; modo=7; RAD2="1";
            break;
          case LO:
            jj_consume_token(LO);
                                                                                                                         modo=7; RAD2="1";
                                                                                                                                              bytesOcupados=bytesOcupados+2;
            break;
          default:
            jj_la1[65] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[66] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case D8:
        bitnumber = jj_consume_token(D8).image;
                                     modo=6;
        jj_consume_token(Coma);
        RAD2 = jj_consume_token(Memoria).image;
        jj_consume_token(Coma);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Memoria:
          jj_consume_token(Memoria);
          break;
        case Datos:
          jj_consume_token(Datos);
          break;
        default:
          jj_la1[67] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(ParentesisC);
                                                                                                               bytesOcupados++;
        break;
      case Memoria:
        RAD2 = jj_consume_token(Memoria).image;
        jj_consume_token(ParentesisC);
                                                modo=2;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Mas:
          jj_consume_token(Mas);
                                                                 modo=3;
          break;
        default:
          jj_la1[68] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[69] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[70] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                countloc=(countloc)+(bytesOcupados*2);
                tabla.setTam(Identi, bytesOcupados*2);
                int RA1=0,RA2=0,dat=0, lsi=0, tam=0,bitnumbe=0;






                if(modo==5 || modo==6 || modo==7) {
                        if(data.substring(0,1).equals("B")) {
                                dat=Integer.parseInt(data.substring(1),2);

                        }
                        else if(data.substring(0,1).equals("0")) {
                                dat=Integer.parseInt(data.substring(1),16);

                        }
                        else if(data.substring(0,1).equals("$")) {
                                dat=Integer.parseInt(data.substring(1),16);

                        }
                        else {  dat=Integer.parseInt(data); }


                }


                if (type==2) {
                        if(data.substring(0,1).equals("B")) {
                                bitnumbe=Integer.parseInt(bitnumber.substring(1),16);
                        }
                        else if(data.substring(0,1).equals("0")) {
                                bitnumbe=Integer.parseInt(bitnumber.substring(1),16);

                        }
                        else if(data.substring(0,1).equals("$")) {
                                bitnumbe=Integer.parseInt(bitnumber.substring(1),16);

                        }
                        else {  bitnumbe=Integer.parseInt(bitnumber); }

                        RA1=Integer.parseInt(RAD1.substring(1));

                }

                if(type==1) {
                        RA1=Integer.parseInt(RAD1.substring(1));
                        RA2=Integer.parseInt(RAD2.substring(1));
                }
                if(DR==0) {

                        ensamblar.LSL(RA1,RA2,dat, lsir, tam, type,modo,bitnumbe);
                }
                if(DR==1) {
                        ensamblar.LSR(RA1,RA2,dat, lsir, tam, type,modo,bitnumbe);
                }
                type=0;
  }

/****************************FIN MATTA*******************/
  static final public void EOR(String id) throws ParseException {
        String tipo="Default";
        EOPMODO=5;
    jj_consume_token(EOR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Punto:
      jj_consume_token(Punto);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BY:
        jj_consume_token(BY);
                           tipo="B"; EOPMODO=4;
        break;
      case LO:
        jj_consume_token(LO);
                                                       tipo="L"; EOPMODO=6;
        break;
      case WO:
        jj_consume_token(WO);
                                                                                   tipo="W"; EOPMODO=5;
        break;
      default:
        jj_la1[71] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[72] = jj_gen;
      ;
    }
    RAD1 = jj_consume_token(Datos).image;
                                                                                                                                 System.out.println("Encontrado RAD1="+RAD1);
    jj_consume_token(Coma);
    EOR_EA(id, tipo);
  }

  static final public void EOR_EA(String id, String tipo) throws ParseException {
        int bytesOcupados=0x1;
        int multi=2;
        int registro1=0;
        int registro2=0;
        int mode=0;
        String number="00";
        int ext=0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Datos:
      RAD2 = jj_consume_token(Datos).image;
                            System.out.println("Encontrado RAD2:"+RAD2);
      break;
    case Guion:
      jj_consume_token(Guion);
      jj_consume_token(ParentesisA);
      RAD2 = jj_consume_token(Memoria).image;
      jj_consume_token(ParentesisC);
                                                                    mode=4;
      break;
    case ParentesisA:
      jj_consume_token(ParentesisA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Memoria:
        RAD2 = jj_consume_token(Memoria).image;
                                      mode=2;
        jj_consume_token(ParentesisC);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Mas:
          jj_consume_token(Mas);
                                                                   mode=3;
          break;
        default:
          jj_la1[73] = jj_gen;
          ;
        }
        break;
      case D16:
        number = jj_consume_token(D16).image;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Coma:
          jj_consume_token(Coma);
          RAD2 = jj_consume_token(Memoria).image;
          jj_consume_token(ParentesisC);
                                                                              mode=5;
          break;
        case ParentesisC:
          jj_consume_token(ParentesisC);
                                                                                                      mode=7;
          jj_consume_token(Punto);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case WO:
            jj_consume_token(WO);
                                                                                                                            bytesOcupados++; RAD2="00";
            break;
          case LO:
            jj_consume_token(LO);
                                                                                                                                                               bytesOcupados+=2; RAD2="01";
            break;
          default:
            jj_la1[74] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[75] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case D8:
        number = jj_consume_token(D8).image;
        jj_consume_token(Coma);
        RAD2 = jj_consume_token(Memoria).image;
        jj_consume_token(Coma);
                                                                     mode=6;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case Datos:
          jj_consume_token(Datos);
          break;
        case Memoria:
          RAD2 = jj_consume_token(Memoria).image;
          break;
        default:
          jj_la1[76] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(ParentesisC);
                                                                                                                           bytesOcupados++;
        break;
      default:
        jj_la1[77] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[78] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                countloc+=bytesOcupados*multi;
                registro1=Integer.parseInt(RAD1.substring(1,RAD1.length()));
                registro2=Integer.parseInt(RAD2.substring(1,RAD2.length()));
                ext=Integer.parseInt(number.substring(1,number.length()),16);
                ensamblar.EOR(registro1,registro2,EOPMODO,mode,ext);
                tabla.setTam(id,bytesOcupados*multi);
  }

/*FIN METODOS INSTRUCCIONES EOR Y LSL-LSR*/

/*METODOS PARA ASIGNAGION DE TAMAÑO Y VALOR*/
  static final public int Tamanio() throws ParseException {
        int mult;
        int TipoDato2;
    jj_consume_token(Punto);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BY:
      jj_consume_token(BY);
                     mult=1;
      break;
    case WO:
      jj_consume_token(WO);
                                    mult=2;
      break;
    case LO:
      jj_consume_token(LO);
                                                   mult=3;
      break;
    default:
      jj_la1[79] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return mult;}
    throw new Error("Missing return statement in function");
  }

  static final public void Valor2(int aux, Token id) throws ParseException {
        int bytes=0;
        String Identi=id.image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case D8:
    case D16:
    case D32:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case D32:
        jj_consume_token(D32);
               bytes=bytes+4;
        break;
      case D16:
        jj_consume_token(D16);
                                      bytes=bytes+2;
        break;
      case D8:
        jj_consume_token(D8);
                                                            bytes=bytes+1;
        break;
      default:
        jj_la1[80] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[81] = jj_gen;
      ;
    }
                switch(aux) {
                case 1 :
                        countloc=(countloc)+(bytes);
                        tabla.setTam(Identi, bytes);
                        break;
                case 2 :
                        countloc=(countloc)+(bytes*2);
                        tabla.setTam(Identi, bytes*2);
                        break;
                case 3 :
                        countloc=(countloc)+(bytes*4);
                        tabla.setTam(Identi, bytes*4);
                        break;
                case 4 :
                        //System.out.println("DIRECTIVAB EQU id "+Identi);
                        break;
                case 5 :
                        //System.out.println("DIRECTIVA  EXT id"+Identi);
                        break;
                case 6 :
                        //System.out.println("DIRECTIVA DEF id "+Identi);
                        break;
                }
  }

  static final public void CONTADORBW(String id,int tipo,Token valor) throws ParseException {
        int valor2=0; String Convertir; int localidades=0; String Tipovalor; String tipoC="";
                Tipovalor=valor.image.substring(0,1);
                //System.out.println("Valores  :"+Tipovalor);
                //int direccion = Contador;
                int total=0;
                if(Tipovalor.equals("B")) {
                        valor2=Integer.parseInt(valor.image.substring(1,valor.image.length()),2);
                }
                if(Tipovalor.equals("$")) {
                        valor2=Integer.parseInt(valor.image.substring(1,valor.image.length()),16);
                }
                if(Tipovalor.equals("0")) {
                        valor2=Integer.parseInt(valor.image.substring(1,valor.image.length()),8);
                }
                if(Tipovalor.equals("1") ||Tipovalor.equals("2") ||Tipovalor.equals("3") ||Tipovalor.equals("4")
                   ||Tipovalor.equals("5") ||Tipovalor.equals("6") ||Tipovalor.equals("7") ||Tipovalor.equals("8")
                   ||Tipovalor.equals("9") )
                {  valor2=Integer.parseInt(valor.image); }
                switch(tipo) {
                case 1 :
                        total= valor2;
                        //localidades=valor2;
                        tipoC=".B";

                        break;
                case 2 :
                        total=2*valor2;
                        //localidades=valor2;
                        tipoC=".W";
                        break;
                case 3 :
                        total= 4*valor2;
                        //localidades=valor2;
                        tipoC=".L";
                        break;
                }
                countloc+=total;
                if (!tabla.existe(id)) {
                        tabla.insertar(id,countloc,tipoC);
                }
                else{
                        System.out.println("Error el ID \u005c""+id+"\u005c"Ya se encuentra");
                        java.lang.System.exit(0);
                }
                tabla.setTam(id, total);
  }

  static final public Token Valor() throws ParseException {
        Token v; String str="";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case D8:
      v = jj_consume_token(D8);
      break;
    case D16:
      v = jj_consume_token(D16);
      break;
    case D32:
      v = jj_consume_token(D32);
      break;
    default:
      jj_la1[82] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return v;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ProyectoFase3TokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[83];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static private int[] jj_la1_5;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
      jj_la1_init_5();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x104100,0x0,0x0,0x0,0x0,0x0,0x0,0x80000000,0xa0,0x0,0x104100,0x0,0xc0,0x0,0x0,0x4100,0x40000000,0x4100,0x80000000,0xc0,0x0,0x0,0x0,0x0,0x4100,0xe0,0x0,0x80000000,0x80000000,0x40000000,0x0,0xc0,0x0,0x0,0x0,0x4100,0x104100,0x80000000,0xc0,0x40000000,0x0,0x4100,0x80000000,0x0,0x80000000,0xe0,0x0,0x0,0x0,0xc0,0x0,0x0,0x0,0x4100,0x40000000,0x4100,0x104100,0x80000000,0xe0,0x0,0xe0,0x0,0x0,0x104100,0x80000000,0xc0,0x0,0x0,0x40000000,0x4100,0x80000000,0xe0,0x0,0x40000000,0xc0,0x0,0x0,0x4100,0x80000000,0xe0,0x104100,0x104100,0x104100,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0xfe00000,0xfc00000,0x20000000,0x0,0x400,0x0,0x20020000,0x0,0x808,0x60000000,0x0,0x0,0x40000000,0x20000004,0x0,0xc0000000,0x808,0xc0000000,0x60000000,0x40000000,0x0,0x400,0x20000004,0x60020004,0x0,0xc0000000,0x0,0x808,0xc0000000,0x60000000,0x40000000,0x0,0x40020004,0x0,0x0,0x60000000,0x40000000,0x4,0x400,0x20000000,0x0,0x400,0x60000000,0xc0000000,0x0,0x808,0xc0000000,0x60000000,0x0,0x0,0x40000000,0x0,0x60020004,0x0,0x400,0x0,0x400,0x0,0x0,0x20020004,0x0,0x808,0x60000000,0x0,0x40000000,0x4,0x0,0x400,0x0,0x0,0x808,0x60000000,0x40000000,0x20000004,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x1040000,0x1040000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x8302000,0x8302000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x300000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x0,0x0,0x0,0x100600,0x100600,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_5() {
      jj_la1_5 = new int[] {0x0,0x8000000,0x8000000,0x8000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public ProyectoFase3(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ProyectoFase3(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ProyectoFase3TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ProyectoFase3(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ProyectoFase3TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ProyectoFase3(ProyectoFase3TokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ProyectoFase3TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[190];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 83; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
          if ((jj_la1_5[i] & (1<<j)) != 0) {
            la1tokens[160+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 190; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
